// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1677774209);
user_pref("browser.search.region", "KE");
user_pref("calendar.caldav.googleResync", 1677774205);
user_pref("calendar.list.sortOrder", "e956e7cc-3072-4110-8209-9b881382c84e");
user_pref("calendar.registry.e956e7cc-3072-4110-8209-9b881382c84e.calendar-main-default", true);
user_pref("calendar.registry.e956e7cc-3072-4110-8209-9b881382c84e.calendar-main-in-composite", true);
user_pref("calendar.registry.e956e7cc-3072-4110-8209-9b881382c84e.disabled", true);
user_pref("calendar.registry.e956e7cc-3072-4110-8209-9b881382c84e.name", "Home");
user_pref("calendar.registry.e956e7cc-3072-4110-8209-9b881382c84e.type", "storage");
user_pref("calendar.registry.e956e7cc-3072-4110-8209-9b881382c84e.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Africa/Nairobi");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1677774213325");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1677774197);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230131132728");
user_pref("extensions.lastAppVersion", "102.7.1");
user_pref("extensions.lastPlatformVersion", "102.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"dfafd1e3-00ac-4c8a-b058-52dc46dac771\",\"google@search.mozilla.org\":\"b522ce8f-c5dc-4ae3-a4be-7e1e1a74a246\",\"ddg@search.mozilla.org\":\"dde1af47-0804-4cf2-9f05-12efed01c119\",\"amazondotcom@search.mozilla.org\":\"4376ba4c-09a9-4279-90ef-b25838fc1a95\",\"wikipedia@search.mozilla.org\":\"327177c6-fd79-48f5-afd1-5046f3d84771\",\"bing@search.mozilla.org\":\"d9302a81-f9c8-4ce2-88f3-0b17a10f34cb\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "c37fb700-0122-4546-a924-1e501f2e8d0");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.7.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "0cd44293-4fdc-4e49-b97c-57d3150ad3a3");
user_pref("toolkit.telemetry.previousBuildID", "20230131132728");
